name: gov_agent
description: "GovAgent - Voice-first AI assistant for Malaysian government portals"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.0.0
  riverpod_annotation: ^3.0.0
  firebase_core: ^4.4.0
  firebase_ai: ^3.8.0
  firebase_auth: ^6.1.4
  record: ^5.1.0
  flutter_soloud: ^3.1.0
  web_socket_channel: ^3.0.1
  permission_handler: ^11.3.0

dependency_overrides:
  record_linux: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^3.0.0
  build_runner: ^2.4.0

flutter:
  uses-material-design: true
